class Country {
  final String id;
  final String name;
  final String icon;

  const Country({required this.id, required this.name, required this.icon});
}

const List<Country> countries = [
  Country(id: "AF", name: "Afghanistan", icon: "🇦🇫"),
  Country(id: "AL", name: "Albania", icon: "🇦🇱"),
  Country(id: "DZ", name: "Algeria", icon: "🇩🇿"),
  Country(id: "AS", name: "American Samoa", icon: "🇦🇸"),
  Country(id: "AD", name: "Andorra", icon: "🇦🇩"),
  Country(id: "AO", name: "Angola", icon: "🇦🇴"),
  Country(id: "AI", name: "Anguilla", icon: "🇦🇮"),
  Country(id: "AQ", name: "Antarctica", icon: "🇦🇶"),
  Country(id: "AG", name: "Antigua and Barbuda", icon: "🇦🇬"),
  Country(id: "AR", name: "Argentina", icon: "🇦🇷"),
  Country(id: "AM", name: "Armenia", icon: "🇦🇲"),
  Country(id: "AW", name: "Aruba", icon: "🇦🇼"),
  Country(id: "AU", name: "Australia", icon: "🇦🇺"),
  Country(id: "AT", name: "Austria", icon: "🇦🇹"),
  Country(id: "AZ", name: "Azerbaijan", icon: "🇦🇿"),
  Country(id: "BS", name: "Bahamas", icon: "🇧🇸"),
  Country(id: "BH", name: "Bahrain", icon: "🇧🇭"),
  Country(id: "BD", name: "Bangladesh", icon: "🇧🇩"),
  Country(id: "BB", name: "Barbados", icon: "🇧🇧"),
  Country(id: "BY", name: "Belarus", icon: "🇧🇾"),
  Country(id: "BE", name: "Belgium", icon: "🇧🇪"),
  Country(id: "BZ", name: "Belize", icon: "🇧🇿"),
  Country(id: "BJ", name: "Benin", icon: "🇧🇯"),
  Country(id: "BM", name: "Bermuda", icon: "🇧🇲"),
  Country(id: "BT", name: "Bhutan", icon: "🇧🇹"),
  Country(id: "BO", name: "Bolivia, Plurinational State of", icon: "🇧🇴"),
  Country(id: "BQ", name: "Bonaire, Sint Eustatius and Saba", icon: "🇧🇶"),
  Country(id: "BA", name: "Bosnia and Herzegovina", icon: "🇧🇦"),
  Country(id: "BW", name: "Botswana", icon: "🇧🇼"),
  Country(id: "BV", name: "Bouvet Island", icon: "🇧🇻"),
  Country(id: "BR", name: "Brazil", icon: "🇧🇷"),
  Country(id: "IO", name: "British Indian Ocean Territory", icon: "🇮🇴"),
  Country(id: "BN", name: "Brunei Darussalam", icon: "🇧🇳"),
  Country(id: "BG", name: "Bulgaria", icon: "🇧🇬"),
  Country(id: "BF", name: "Burkina Faso", icon: "🇧🇫"),
  Country(id: "BI", name: "Burundi", icon: "🇧🇮"),
  Country(id: "CV", name: "Cabo Verde", icon: "🇨🇻"),
  Country(id: "KH", name: "Cambodia", icon: "🇰🇭"),
  Country(id: "CM", name: "Cameroon", icon: "🇨🇲"),
  Country(id: "CA", name: "Canada", icon: "🇨🇦"),
  Country(id: "KY", name: "Cayman Islands", icon: "🇰🇾"),
  Country(id: "CF", name: "Central African Republic", icon: "🇨🇫"),
  Country(id: "TD", name: "Chad", icon: "🇹🇩"),
  Country(id: "CL", name: "Chile", icon: "🇨🇱"),
  Country(id: "CN", name: "China", icon: "🇨🇳"),
  Country(id: "CX", name: "Christmas Island", icon: "🇨🇽"),
  Country(id: "CC", name: "Cocos (Keeling) Islands", icon: "🇨🇨"),
  Country(id: "CO", name: "Colombia", icon: "🇨🇴"),
  Country(id: "KM", name: "Comoros", icon: "🇰🇲"),
  Country(id: "CG", name: "Congo", icon: "🇨🇬"),
  Country(id: "CD", name: "Congo, The Democratic Republic of the", icon: "🇨🇩"),
  Country(id: "CK", name: "Cook Islands", icon: "🇨🇰"),
  Country(id: "CR", name: "Costa Rica", icon: "🇨🇷"),
  Country(id: "HR", name: "Croatia", icon: "🇭🇷"),
  Country(id: "CU", name: "Cuba", icon: "🇨🇺"),
  Country(id: "CW", name: "Curaçao", icon: "🇨🇼"),
  Country(id: "CY", name: "Cyprus", icon: "🇨🇾"),
  Country(id: "CZ", name: "Czechia", icon: "🇨🇿"),
  Country(id: "CI", name: "Côte d'Ivoire", icon: "🇨🇮"),
  Country(id: "DK", name: "Denmark", icon: "🇩🇰"),
  Country(id: "DJ", name: "Djibouti", icon: "🇩🇯"),
  Country(id: "DM", name: "Dominica", icon: "🇩🇲"),
  Country(id: "DO", name: "Dominican Republic", icon: "🇩🇴"),
  Country(id: "EC", name: "Ecuador", icon: "🇪🇨"),
  Country(id: "EG", name: "Egypt", icon: "🇪🇬"),
  Country(id: "SV", name: "El Salvador", icon: "🇸🇻"),
  Country(id: "GQ", name: "Equatorial Guinea", icon: "🇬🇶"),
  Country(id: "ER", name: "Eritrea", icon: "🇪🇷"),
  Country(id: "EE", name: "Estonia", icon: "🇪🇪"),
  Country(id: "SZ", name: "Eswatini", icon: "🇸🇿"),
  Country(id: "ET", name: "Ethiopia", icon: "🇪🇹"),
  Country(id: "FK", name: "Falkland Islands (Malvinas)", icon: "🇫🇰"),
  Country(id: "FO", name: "Faroe Islands", icon: "🇫🇴"),
  Country(id: "FJ", name: "Fiji", icon: "🇫🇯"),
  Country(id: "FI", name: "Finland", icon: "🇫🇮"),
  Country(id: "FR", name: "France", icon: "🇫🇷"),
  Country(id: "GF", name: "French Guiana", icon: "🇬🇫"),
  Country(id: "PF", name: "French Polynesia", icon: "🇵🇫"),
  Country(id: "TF", name: "French Southern Territories", icon: "🇹🇫"),
  Country(id: "GA", name: "Gabon", icon: "🇬🇦"),
  Country(id: "GM", name: "Gambia", icon: "🇬🇲"),
  Country(id: "GE", name: "Georgia", icon: "🇬🇪"),
  Country(id: "DE", name: "Germany", icon: "🇩🇪"),
  Country(id: "GH", name: "Ghana", icon: "🇬🇭"),
  Country(id: "GI", name: "Gibraltar", icon: "🇬🇮"),
  Country(id: "GR", name: "Greece", icon: "🇬🇷"),
  Country(id: "GL", name: "Greenland", icon: "🇬🇱"),
  Country(id: "GD", name: "Grenada", icon: "🇬🇩"),
  Country(id: "GP", name: "Guadeloupe", icon: "🇬🇵"),
  Country(id: "GU", name: "Guam", icon: "🇬🇺"),
  Country(id: "GT", name: "Guatemala", icon: "🇬🇹"),
  Country(id: "GG", name: "Guernsey", icon: "🇬🇬"),
  Country(id: "GN", name: "Guinea", icon: "🇬🇳"),
  Country(id: "GW", name: "Guinea-Bissau", icon: "🇬🇼"),
  Country(id: "GY", name: "Guyana", icon: "🇬🇾"),
  Country(id: "HT", name: "Haiti", icon: "🇭🇹"),
  Country(id: "HM", name: "Heard Island and McDonald Islands", icon: "🇭🇲"),
  Country(id: "VA", name: "Holy See (Vatican City State)", icon: "🇻🇦"),
  Country(id: "HN", name: "Honduras", icon: "🇭🇳"),
  Country(id: "HK", name: "Hong Kong", icon: "🇭🇰"),
  Country(id: "HU", name: "Hungary", icon: "🇭🇺"),
  Country(id: "IS", name: "Iceland", icon: "🇮🇸"),
  Country(id: "IN", name: "India", icon: "🇮🇳"),
  Country(id: "ID", name: "Indonesia", icon: "🇮🇩"),
  Country(id: "IR", name: "Iran, Islamic Republic of", icon: "🇮🇷"),
  Country(id: "IQ", name: "Iraq", icon: "🇮🇶"),
  Country(id: "IE", name: "Ireland", icon: "🇮🇪"),
  Country(id: "IM", name: "Isle of Man", icon: "🇮🇲"),
  Country(id: "IL", name: "Israel", icon: "🇮🇱"),
  Country(id: "IT", name: "Italy", icon: "🇮🇹"),
  Country(id: "JM", name: "Jamaica", icon: "🇯🇲"),
  Country(id: "JP", name: "Japan", icon: "🇯🇵"),
  Country(id: "JE", name: "Jersey", icon: "🇯🇪"),
  Country(id: "JO", name: "Jordan", icon: "🇯🇴"),
  Country(id: "KZ", name: "Kazakhstan", icon: "🇰🇿"),
  Country(id: "KE", name: "Kenya", icon: "🇰🇪"),
  Country(id: "KI", name: "Kiribati", icon: "🇰🇮"),
  Country(id: "KP", name: "Korea, Democratic People's Republic of", icon: "🇰🇵"),
  Country(id: "KR", name: "Korea, Republic of", icon: "🇰🇷"),
  Country(id: "KW", name: "Kuwait", icon: "🇰🇼"),
  Country(id: "KG", name: "Kyrgyzstan", icon: "🇰🇬"),
  Country(id: "LA", name: "Lao People's Democratic Republic", icon: "🇱🇦"),
  Country(id: "LV", name: "Latvia", icon: "🇱🇻"),
  Country(id: "LB", name: "Lebanon", icon: "🇱🇧"),
  Country(id: "LS", name: "Lesotho", icon: "🇱🇸"),
  Country(id: "LR", name: "Liberia", icon: "🇱🇷"),
  Country(id: "LY", name: "Libya", icon: "🇱🇾"),
  Country(id: "LI", name: "Liechtenstein", icon: "🇱🇮"),
  Country(id: "LT", name: "Lithuania", icon: "🇱🇹"),
  Country(id: "LU", name: "Luxembourg", icon: "🇱🇺"),
  Country(id: "MO", name: "Macao", icon: "🇲🇴"),
  Country(id: "MG", name: "Madagascar", icon: "🇲🇬"),
  Country(id: "MW", name: "Malawi", icon: "🇲🇼"),
  Country(id: "MY", name: "Malaysia", icon: "🇲🇾"),
  Country(id: "MV", name: "Maldives", icon: "🇲🇻"),
  Country(id: "ML", name: "Mali", icon: "🇲🇱"),
  Country(id: "MT", name: "Malta", icon: "🇲🇹"),
  Country(id: "MH", name: "Marshall Islands", icon: "🇲🇭"),
  Country(id: "MQ", name: "Martinique", icon: "🇲🇶"),
  Country(id: "MR", name: "Mauritania", icon: "🇲🇷"),
  Country(id: "MU", name: "Mauritius", icon: "🇲🇺"),
  Country(id: "YT", name: "Mayotte", icon: "🇾🇹"),
  Country(id: "MX", name: "Mexico", icon: "🇲🇽"),
  Country(id: "FM", name: "Micronesia, Federated States of", icon: "🇫🇲"),
  Country(id: "MD", name: "Moldova, Republic of", icon: "🇲🇩"),
  Country(id: "MC", name: "Monaco", icon: "🇲🇨"),
  Country(id: "MN", name: "Mongolia", icon: "🇲🇳"),
  Country(id: "ME", name: "Montenegro", icon: "🇲🇪"),
  Country(id: "MS", name: "Montserrat", icon: "🇲🇸"),
  Country(id: "MA", name: "Morocco", icon: "🇲🇦"),
  Country(id: "MZ", name: "Mozambique", icon: "🇲🇿"),
  Country(id: "MM", name: "Myanmar", icon: "🇲🇲"),
  Country(id: "NA", name: "Namibia", icon: "🇳🇦"),
  Country(id: "NR", name: "Nauru", icon: "🇳🇷"),
  Country(id: "NP", name: "Nepal", icon: "🇳🇵"),
  Country(id: "NL", name: "Netherlands", icon: "🇳🇱"),
  Country(id: "NC", name: "New Caledonia", icon: "🇳🇨"),
  Country(id: "NZ", name: "New Zealand", icon: "🇳🇿"),
  Country(id: "NI", name: "Nicaragua", icon: "🇳🇮"),
  Country(id: "NE", name: "Niger", icon: "🇳🇪"),
  Country(id: "NG", name: "Nigeria", icon: "🇳🇬"),
  Country(id: "NU", name: "Niue", icon: "🇳🇺"),
  Country(id: "NF", name: "Norfolk Island", icon: "🇳🇫"),
  Country(id: "MK", name: "North Macedonia", icon: "🇲🇰"),
  Country(id: "MP", name: "Northern Mariana Islands", icon: "🇲🇵"),
  Country(id: "NO", name: "Norway", icon: "🇳🇴"),
  Country(id: "OM", name: "Oman", icon: "🇴🇲"),
  Country(id: "PK", name: "Pakistan", icon: "🇵🇰"),
  Country(id: "PW", name: "Palau", icon: "🇵🇼"),
  Country(id: "PS", name: "Palestine, State of", icon: "🇵🇸"),
  Country(id: "PA", name: "Panama", icon: "🇵🇦"),
  Country(id: "PG", name: "Papua New Guinea", icon: "🇵🇬"),
  Country(id: "PY", name: "Paraguay", icon: "🇵🇾"),
  Country(id: "PE", name: "Peru", icon: "🇵🇪"),
  Country(id: "PH", name: "Philippines", icon: "🇵🇭"),
  Country(id: "PN", name: "Pitcairn", icon: "🇵🇳"),
  Country(id: "PL", name: "Poland", icon: "🇵🇱"),
  Country(id: "PT", name: "Portugal", icon: "🇵🇹"),
  Country(id: "PR", name: "Puerto Rico", icon: "🇵🇷"),
  Country(id: "QA", name: "Qatar", icon: "🇶🇦"),
  Country(id: "RO", name: "Romania", icon: "🇷🇴"),
  Country(id: "RU", name: "Russian Federation", icon: "🇷🇺"),
  Country(id: "RW", name: "Rwanda", icon: "🇷🇼"),
  Country(id: "RE", name: "Réunion", icon: "🇷🇪"),
  Country(id: "BL", name: "Saint Barthélemy", icon: "🇧🇱"),
  Country(id: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", icon: "🇸🇭"),
  Country(id: "KN", name: "Saint Kitts and Nevis", icon: "🇰🇳"),
  Country(id: "LC", name: "Saint Lucia", icon: "🇱🇨"),
  Country(id: "MF", name: "Saint Martin (French part)", icon: "🇲🇫"),
  Country(id: "PM", name: "Saint Pierre and Miquelon", icon: "🇵🇲"),
  Country(id: "VC", name: "Saint Vincent and the Grenadines", icon: "🇻🇨"),
  Country(id: "WS", name: "Samoa", icon: "🇼🇸"),
  Country(id: "SM", name: "San Marino", icon: "🇸🇲"),
  Country(id: "ST", name: "Sao Tome and Principe", icon: "🇸🇹"),
  Country(id: "SA", name: "Saudi Arabia", icon: "🇸🇦"),
  Country(id: "SN", name: "Senegal", icon: "🇸🇳"),
  Country(id: "RS", name: "Serbia", icon: "🇷🇸"),
  Country(id: "SC", name: "Seychelles", icon: "🇸🇨"),
  Country(id: "SL", name: "Sierra Leone", icon: "🇸🇱"),
  Country(id: "SG", name: "Singapore", icon: "🇸🇬"),
  Country(id: "SX", name: "Sint Maarten (Dutch part)", icon: "🇸🇽"),
  Country(id: "SK", name: "Slovakia", icon: "🇸🇰"),
  Country(id: "SI", name: "Slovenia", icon: "🇸🇮"),
  Country(id: "SB", name: "Solomon Islands", icon: "🇸🇧"),
  Country(id: "SO", name: "Somalia", icon: "🇸🇴"),
  Country(id: "ZA", name: "South Africa", icon: "🇿🇦"),
  Country(id: "GS", name: "South Georgia and the South Sandwich Islands", icon: "🇬🇸"),
  Country(id: "SS", name: "South Sudan", icon: "🇸🇸"),
  Country(id: "ES", name: "Spain", icon: "🇪🇸"),
  Country(id: "LK", name: "Sri Lanka", icon: "🇱🇰"),
  Country(id: "SD", name: "Sudan", icon: "🇸🇩"),
  Country(id: "SR", name: "Suriname", icon: "🇸🇷"),
  Country(id: "SJ", name: "Svalbard and Jan Mayen", icon: "🇸🇯"),
  Country(id: "SE", name: "Sweden", icon: "🇸🇪"),
  Country(id: "CH", name: "Switzerland", icon: "🇨🇭"),
  Country(id: "SY", name: "Syrian Arab Republic", icon: "🇸🇾"),
  Country(id: "TW", name: "Taiwan, Province of China", icon: "🇹🇼"),
  Country(id: "TJ", name: "Tajikistan", icon: "🇹🇯"),
  Country(id: "TZ", name: "Tanzania, United Republic of", icon: "🇹🇿"),
  Country(id: "TH", name: "Thailand", icon: "🇹🇭"),
  Country(id: "TL", name: "Timor-Leste", icon: "🇹🇱"),
  Country(id: "TG", name: "Togo", icon: "🇹🇬"),
  Country(id: "TK", name: "Tokelau", icon: "🇹🇰"),
  Country(id: "TO", name: "Tonga", icon: "🇹🇴"),
  Country(id: "TT", name: "Trinidad and Tobago", icon: "🇹🇹"),
  Country(id: "TN", name: "Tunisia", icon: "🇹🇳"),
  Country(id: "TR", name: "Turkey", icon: "🇹🇷"),
  Country(id: "TM", name: "Turkmenistan", icon: "🇹🇲"),
  Country(id: "TC", name: "Turks and Caicos Islands", icon: "🇹🇨"),
  Country(id: "TV", name: "Tuvalu", icon: "🇹🇻"),
  Country(id: "UG", name: "Uganda", icon: "🇺🇬"),
  Country(id: "UA", name: "Ukraine", icon: "🇺🇦"),
  Country(id: "AE", name: "United Arab Emirates", icon: "🇦🇪"),
  Country(id: "GB", name: "United Kingdom", icon: "🇬🇧"),
  Country(id: "US", name: "United States", icon: "🇺🇸"),
  Country(id: "UM", name: "United States Minor Outlying Islands", icon: "🇺🇲"),
  Country(id: "UY", name: "Uruguay", icon: "🇺🇾"),
  Country(id: "UZ", name: "Uzbekistan", icon: "🇺🇿"),
  Country(id: "VU", name: "Vanuatu", icon: "🇻🇺"),
  Country(id: "VE", name: "Venezuela, Bolivarian Republic of", icon: "🇻🇪"),
  Country(id: "VN", name: "Viet Nam", icon: "🇻🇳"),
  Country(id: "VG", name: "Virgin Islands, British", icon: "🇻🇬"),
  Country(id: "VI", name: "Virgin Islands, U.S.", icon: "🇻🇮"),
  Country(id: "WF", name: "Wallis and Futuna", icon: "🇼🇫"),
  Country(id: "EH", name: "Western Sahara", icon: "🇪🇭"),
  Country(id: "YE", name: "Yemen", icon: "🇾🇪"),
  Country(id: "ZM", name: "Zambia", icon: "🇿🇲"),
  Country(id: "ZW", name: "Zimbabwe", icon: "🇿🇼"),
  Country(id: "AX", name: "Åland Islands", icon: "🇦🇽"),
];