class Language {
  final String id;
  final String name;
  final String icon;

  const Language({
    required this.id,
    required this.name,
    required this.icon,
  });
}

const List<Language> languages = [
  Language(id: "ar", name: "Arabic", icon: "🏳️"),
  Language(id: "as-IN", name: "Assamese", icon: "🇮🇳"),
  Language(id: "bg-BG", name: "Bulgarian", icon: "🇧🇬"),
  Language(id: "bn-BD", name: "Bengali-BD", icon: "🇧🇩"),
  Language(id: "bn-IN", name: "Bengali-IN", icon: "🇮🇳"),
  Language(id: "brx-IN", name: "Bodo", icon: "🇮🇳"),
  Language(id: "bs-BA", name: "Bosnian", icon: "🇧🇦"),
  Language(id: "ca-ES", name: "Catalan", icon: "🇪🇸"),
  Language(id: "cs-CZ", name: "Czech", icon: "🇨🇿"),
  Language(id: "cy-GB", name: "Welsh", icon: "🇬🇧"),
  Language(id: "da-DK", name: "Danish", icon: "🇩🇰"),
  Language(id: "de-DE", name: "German", icon: "🇩🇪"),
  Language(id: "doi-IN", name: "Dogri", icon: "🇮🇳"),
  Language(id: "el-GR", name: "Greek", icon: "🇬🇷"),
  Language(id: "en-US", name: "English-US", icon: "🇺🇸"),
  Language(id: "en-GB", name: "English-GB", icon: "🇬🇧"),
  Language(id: "en-AU", name: "English-AU", icon: "🇦🇺"),
  Language(id: "en-NG", name: "English-NG", icon: "🇳🇬"),
  Language(id: "en-IN", name: "English-IN", icon: "🇮🇳"),
  Language(id: "es-ES", name: "Spanish-ES", icon: "🇪🇸"),
  Language(id: "es-US", name: "Spanish-US", icon: "🇺🇸"),
  Language(id: "et-EE", name: "Estonian", icon: "🇪🇪"),
  Language(id: "fa-IR", name: "Persian", icon: "🇮🇷"),
  Language(id: "fi-FI", name: "Finnish", icon: "🇫🇮"),
  Language(id: "fil-PH", name: "Filipino", icon: "🇵🇭"),
  Language(id: "fr-FR", name: "French-FR", icon: "🇫🇷"),
  Language(id: "fr-CA", name: "French-CA", icon: "🇨🇦"),
  Language(id: "gu-IN", name: "Gujarati", icon: "🇮🇳"),
  Language(id: "he-IL", name: "Hebrew", icon: "🇮🇱"),
  Language(id: "hi-IN", name: "Hindi", icon: "🇮🇳"),
  Language(id: "hr-HR", name: "Croatian", icon: "🇭🇷"),
  Language(id: "hu-HU", name: "Hungarian", icon: "🇭🇺"),
  Language(id: "id-ID", name: "Indonesian", icon: "🇮🇩"),
  Language(id: "is-IS", name: "Icelandic", icon: "🇮🇸"),
  Language(id: "it-IT", name: "Italian", icon: "🇮🇹"),
  Language(id: "ja-JP", name: "Japanese", icon: "🇯🇵"),
  Language(id: "jv-ID", name: "Javanese", icon: "🇮🇩"),
  Language(id: "km-KH", name: "Khmer", icon: "🇰🇭"),
  Language(id: "kn-IN", name: "Kannada", icon: "🇮🇳"),
  Language(id: "kok-IN", name: "Konkani", icon: "🇮🇳"),
  Language(id: "ko-KR", name: "Korean", icon: "🇰🇷"),
  Language(id: "ks-IN", name: "Kashmiri", icon: "🇮🇳"),
  Language(id: "lt-LT", name: "Lithuanian", icon: "🇱🇹"),
  Language(id: "lv-LV", name: "Latvian", icon: "🇱🇻"),
  Language(id: "mai-IN", name: "Maithili", icon: "🇮🇳"),
  Language(id: "ml-IN", name: "Malayalam", icon: "🇮🇳"),
  Language(id: "mni-IN", name: "Manipuri", icon: "🇮🇳"),
  Language(id: "mr-IN", name: "Marathi", icon: "🇮🇳"),
  Language(id: "ms-MY", name: "Malay", icon: "🇲🇾"),
  Language(id: "nb-NO", name: "Norwegian Bokmål", icon: "🇳🇴"),
  Language(id: "ne-NP", name: "Nepali", icon: "🇳🇵"),
  Language(id: "nl-NL", name: "Dutch-NL", icon: "🇳🇱"),
  Language(id: "nl-BE", name: "Dutch-BE", icon: "🇧🇪"),
  Language(id: "or-IN", name: "Odia", icon: "🇮🇳"),
  Language(id: "pa-IN", name: "Punjabi", icon: "🇮🇳"),
  Language(id: "pl-PL", name: "Polish", icon: "🇵🇱"),
  Language(id: "pt-PT", name: "Portuguese-PT", icon: "🇵🇹"),
  Language(id: "pt-BR", name: "Portuguese-BR", icon: "🇧🇷"),
  Language(id: "ro-RO", name: "Romanian", icon: "🇷🇴"),
  Language(id: "ru-RU", name: "Russian", icon: "🇷🇺"),
  Language(id: "sa-IN", name: "Sanskrit", icon: "🇮🇳"),
  Language(id: "sat-IN", name: "Santali", icon: "🇮🇳"),
  Language(id: "sd-IN", name: "Sindhi", icon: "🇮🇳"),
  Language(id: "si-LK", name: "Sinhala", icon: "🇱🇰"),
  Language(id: "sk-SK", name: "Slovak", icon: "🇸🇰"),
  Language(id: "sl-SI", name: "Slovenian", icon: "🇸🇮"),
  Language(id: "sq-AL", name: "Albanian", icon: "🇦🇱"),
  Language(id: "sr-RS", name: "Serbian", icon: "🇷🇸"),
  Language(id: "su-ID", name: "Sundanese", icon: "🇮🇩"),
  Language(id: "sv-SE", name: "Swedish", icon: "🇸🇪"),
  Language(id: "sw-KE", name: "Swahili", icon: "🇰🇪"),
  Language(id: "ta-IN", name: "Tamil", icon: "🇮🇳"),
  Language(id: "te-IN", name: "Telugu", icon: "🇮🇳"),
  Language(id: "th-TH", name: "Thai", icon: "🇹🇭"),
  Language(id: "tr-TR", name: "Turkish", icon: "🇹🇷"),
  Language(id: "uk-UA", name: "Ukrainian", icon: "🇺🇦"),
  Language(id: "ur-IN", name: "Urdu-IN", icon: "🇮🇳"),
  Language(id: "ur-PK", name: "Urdu-PK", icon: "🇵🇰"),
  Language(id: "vi-VN", name: "Vietnamese", icon: "🇻🇳"),
  Language(id: "yue-HK", name: "Cantonese", icon: "🇭🇰"),
  Language(id: "zh-TW", name: "Chinese-TW", icon: "🇹🇼"),
  Language(id: "zh-CN", name: "Chinese-CN", icon: "🇨🇳"),
];
