class LocationType {
  final String id;
  final String name;
  final String icon;

  const LocationType({
    required this.id,
    required this.name,
    required this.icon,
  });
}

const List<LocationType> locationTypes = [
  LocationType(id: "airport", name: "Airport", icon: "✈️"),
  LocationType(id: "amusement_park", name: "Amusement Park", icon: "🎢"),
  LocationType(id: "aquarium", name: "Aquarium", icon: "🐠"),
  LocationType(id: "art_gallery", name: "Art Gallery", icon: "🖼️"),
  LocationType(id: "atm", name: "ATM / Bank", icon: "🏧"),
  LocationType(id: "bakery", name: "Bakery", icon: "🥐"),
  LocationType(id: "bank", name: "Bank", icon: "🏦"),
  LocationType(id: "bar", name: "Bar / Pub", icon: "🍺"),
  LocationType(id: "beach", name: "Beach", icon: "🏖️"),
  LocationType(id: "beauty_salon", name: "Beauty Salon", icon: "💇"),
  LocationType(id: "bookstore", name: "Bookstore", icon: "📚"),
  LocationType(id: "cafe", name: "Cafe", icon: "☕"),
  LocationType(id: "campground", name: "Campground", icon: "🏕️"),
  LocationType(id: "car_rental", name: "Car Rental", icon: "🚘"),
  LocationType(id: "church", name: "Church", icon: "⛪"),
  LocationType(id: "cinema", name: "Cinema", icon: "🎬"),
  LocationType(id: "clinic", name: "Clinic", icon: "🏥"),
  LocationType(id: "convenience_store", name: "Convenience Store", icon: "🏪"),
  LocationType(id: "coworking", name: "Coworking Space", icon: "💻"),
  LocationType(id: "embassy", name: "Embassy", icon: "🏛️"),
  LocationType(id: "fire_station", name: "Fire Station", icon: "🚒"),
  LocationType(id: "gas_station", name: "Gas Station", icon: "⛽"),
  LocationType(id: "garden", name: "Garden", icon: "🌺"),
  LocationType(id: "government_office", name: "Government Office", icon: "🏢"),
  LocationType(id: "gym", name: "Gym / Fitness", icon: "🏋️"),
  LocationType(id: "harbor", name: "Harbor / Port", icon: "⚓"),
  LocationType(id: "historical_site", name: "Historical Site", icon: "🏰"),
  LocationType(id: "hostel", name: "Hostel", icon: "🛏️"),
  LocationType(id: "hotel", name: "Hotel", icon: "🏨"),
  LocationType(id: "internet_cafe", name: "Internet Cafe", icon: "🌐"),
  LocationType(id: "karaoke", name: "Karaoke", icon: "🎤"),
  LocationType(id: "lake", name: "Lake", icon: "🏞️"),
  LocationType(id: "landmark", name: "Landmark", icon: "📍"),
  LocationType(id: "library", name: "Library", icon: "📚"),
  LocationType(id: "market", name: "Market", icon: "🏪"),
  LocationType(id: "mosque", name: "Mosque", icon: "🕌"),
  LocationType(id: "mountain", name: "Mountain", icon: "🏔️"),
  LocationType(id: "museum", name: "Museum", icon: "🏛️"),
  LocationType(id: "night_market", name: "Night Market", icon: "🌙🛍️"),
  LocationType(id: "other", name: "Other", icon: "📌"),
  LocationType(id: "park", name: "Park", icon: "🏞️"),
  LocationType(id: "parking", name: "Parking Lot", icon: "🅿️"),
  LocationType(id: "pet_store", name: "Pet Store", icon: "🐾"),
  LocationType(id: "pharmacy", name: "Pharmacy", icon: "💊"),
  LocationType(id: "playground", name: "Playground", icon: "🛝"),
  LocationType(id: "police_station", name: "Police Station", icon: "👮"),
  LocationType(id: "post_office", name: "Post Office", icon: "📮"),
  LocationType(id: "print_shop", name: "Printing Shop", icon: "🖨️"),
  LocationType(id: "recycling", name: "Recycling Center", icon: "♻️"),
  LocationType(id: "restaurant", name: "Restaurant", icon: "🍽️"),
  LocationType(id: "shopping_store", name: "Shopping Store", icon: "🛍️"),
  LocationType(id: "spa", name: "Spa / Massage", icon: "💆"),
  LocationType(id: "stadium", name: "Stadium", icon: "🏟️"),
  LocationType(id: "station", name: "Train / Bus Station", icon: "🚉"),
  LocationType(id: "supermarket", name: "Supermarket", icon: "🛒"),
  LocationType(id: "swimming_pool", name: "Swimming Pool", icon: "🏊"),
  LocationType(id: "tattoo", name: "Tattoo Studio", icon: "🧑‍🎤"),
  LocationType(id: "temple", name: "Temple", icon: "🛕"),
  LocationType(id: "theme_park", name: "Theme Park", icon: "🎡"),
  LocationType(id: "tourist_info", name: "Tourist Info Center", icon: "ℹ️"),
  LocationType(id: "university", name: "University", icon: "🎓"),
  LocationType(id: "vet_clinic", name: "Veterinary Clinic", icon: "🐶"),
  LocationType(id: "waterpark", name: "Waterpark", icon: "🌊"),
  LocationType(id: "wedding_hall", name: "Wedding Hall", icon: "💒"),
  LocationType(id: "winery", name: "Winery / Vineyard", icon: "🍷"),
  LocationType(id: "zoo", name: "Zoo / Aquarium", icon: "🦁"),
];